# Generated by Django 5.2.8 on 2026-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAReglaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EXACTA', 'Pregunta exacta'), ('PATRON', 'Patrón')], db_index=True, default='EXACTA', max_length=20)),
                ('pregunta', models.TextField()),
                ('pregunta_normalizada', models.TextField(db_index=True)),
                ('tema', models.CharField(max_length=50)),
                ('operacion', models.CharField(default='listar', max_length=30)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('cantidad', models.CharField(default='varios', max_length=20)),
                ('orden', models.CharField(default='ninguno', max_length=20)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('veces_usada', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
