# Generated by Django 5.2.8 on 2026-10-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_local', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='iareglasemantica',
            constraint=models.UniqueConstraint(fields=('tipo', 'pregunta_normalizada'), name='uniq_ia_regla_tipo_pregunta_normalizada'),
        ),
    ]
