# Generated by Django 5.2.8 on 2026-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmitalFolderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_path', models.CharField(default='/home/max/condocdat/doc', max_length=1024)),
                ('current_number', models.PositiveIntegerField(default=293)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración creador carpetas transmital',
                'verbose_name_plural': 'Configuración creador carpetas transmital',
            },
        ),
        migrations.CreateModel(
            name='TransmitalFolderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=128, unique=True)),
                ('folder_path', models.CharField(max_length=2048, unique=True)),
                ('sequence_number', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carpeta transmital creada',
                'verbose_name_plural': 'Carpetas transmital creadas',
                'ordering': ['-sequence_number'],
            },
        ),
    ]
