# Generated by Django 5.2.8 on 2026-04-29 22:12

import transmital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmital', '0002_transmitalfolderconfig_transmitalfolderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmital',
            name='fecha_caratula',
            field=models.DateField(blank=True, default=transmital.models.default_fecha_caratula, null=True),
        ),
    ]
