# Generated by Django 5.2.8 on 2026-05-03 21:49

import transmital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmital', '0004_update_default_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitalfolderconfig',
            name='base_path',
            field=models.CharField(default=transmital.models.default_transmital_folder_base_path, max_length=1024),
        ),
    ]
