# Generated by Django 5.2.8 on 2026-09-27 03:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transmital', '0005_transmital_folder_config_doc_root_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(db_index=True, help_text='Identificador determinístico utilizado para evitar duplicados durante backfill y reconciliaciones.', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('SENT', 'Enviado'), ('RECEIVED', 'Recibido'), ('STATUS_CHANGED', 'Cambio de estado'), ('REVISION_CHANGED', 'Cambio de revisión'), ('RESPONSE', 'Respuesta'), ('ATTACHED', 'Archivo adjuntado'), ('LINKED', 'Relación establecida'), ('UNLINKED', 'Relación eliminada'), ('IMPORTED', 'Importado'), ('SUPERSEDED', 'Reemplazado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('ISSUED', 'Emitido'), ('DELETED', 'Eliminado')], db_index=True, max_length=32)),
                ('origin', models.CharField(choices=[('BACKFILL', 'Reconstrucción histórica'), ('LIVE', 'Registro en línea'), ('IMPORT', 'Importación externa'), ('RECONCILIATION', 'Reconciliación'), ('MANUAL', 'Registro manual')], db_index=True, default='LIVE', max_length=20)),
                ('data_quality', models.CharField(choices=[('CONFIRMED', 'Confirmado'), ('RECONSTRUCTED', 'Reconstruido'), ('PARTIAL', 'Parcial'), ('INFERRED', 'Inferido')], db_index=True, default='CONFIRMED', max_length=20)),
                ('source_completeness', models.BooleanField(default=True, help_text='False cuando sabemos que el contexto histórico de la fuente es incompleto.')),
                ('event_date', models.DateField(db_index=True, help_text='Fecha funcional en que ocurrió el evento.')),
                ('event_datetime', models.DateTimeField(blank=True, db_index=True, help_text='Fecha/hora real cuando la fuente la entrega. No debe inventarse para registros que solo tienen fecha.', null=True)),
                ('date_precision', models.CharField(choices=[('DATE', 'Solo fecha'), ('DATETIME', 'Fecha y hora')], default='DATE', max_length=10)),
                ('date_source', models.CharField(blank=True, default='', help_text='Campo fuente de la fecha. Ej: Document.date, Transmital.fecha_envio, RDIRecord.created_at.', max_length=128)),
                ('observed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_app', models.CharField(db_index=True, max_length=50)),
                ('source_model', models.CharField(db_index=True, max_length=80)),
                ('source_pk', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source_key', models.CharField(db_index=True, help_text='Identidad funcional estable del registro. Ej: código documental, RDI-184, TTAL-00184.', max_length=512)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('summary', models.TextField(blank=True, default='', help_text='Resumen factual y breve del evento. No almacenar aquí documentos completos.')),
                ('status_before', models.CharField(blank=True, default='', max_length=128)),
                ('status_after', models.CharField(blank=True, default='', max_length=128)),
                ('revision_before', models.CharField(blank=True, default='', max_length=128)),
                ('revision_after', models.CharField(blank=True, default='', max_length=128)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Campos que cambiaron y valores anterior/nuevo.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información auxiliar específica de cada tipo de evento.')),
                ('search_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento del proyecto',
                'verbose_name_plural': 'Eventos del proyecto',
                'ordering': ['event_date', 'event_datetime', 'id'],
                'indexes': [models.Index(fields=['event_date', 'event_type'], name='trace_date_type_idx'), models.Index(fields=['source_app', 'source_model', 'source_pk'], name='trace_source_idx'), models.Index(fields=['source_key', 'event_date'], name='trace_key_date_idx'), models.Index(fields=['data_quality', 'event_date'], name='trace_quality_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='TraceSourceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('TRANSMITTAL', 'Transmittals'), ('FOLDER', 'Carpetas'), ('DOCUMENT', 'Documentos'), ('ATTACHMENT', 'Adjuntos'), ('FOLDER_FILE', 'Archivos de carpeta'), ('RDI', 'RDI'), ('PLAN', 'Planos')], db_index=True, max_length=32)),
                ('coverage_start', models.DateField(db_index=True)),
                ('coverage_end', models.DateField(blank=True, db_index=True, null=True)),
                ('coverage_status', models.CharField(choices=[('COMPLETE', 'Completa'), ('PARTIAL', 'Parcial'), ('UNKNOWN', 'Desconocida')], db_index=True, default='UNKNOWN', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('basis', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cobertura histórica de fuente',
                'verbose_name_plural': 'Coberturas históricas de fuentes',
                'ordering': ['source_type', 'coverage_start'],
                'indexes': [models.Index(fields=['source_type', 'coverage_start', 'coverage_end'], name='trace_coverage_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'coverage_start'), name='uniq_trace_source_period'), models.CheckConstraint(condition=models.Q(('coverage_end__isnull', True), ('coverage_end__gte', models.F('coverage_start')), _connector='OR'), name='trace_coverage_dates_ok')],
            },
        ),
        migrations.CreateModel(
            name='ProjectEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('TRANSMITTAL', 'Transmittal'), ('FOLDER', 'Carpeta'), ('DOCUMENT', 'Documento'), ('ATTACHMENT', 'Adjunto de documento'), ('FOLDER_FILE', 'Archivo de carpeta'), ('RDI', 'RDI'), ('PLAN', 'Plano')], db_index=True, max_length=32)),
                ('entity_app', models.CharField(blank=True, default='', max_length=50)),
                ('entity_model', models.CharField(blank=True, default='', max_length=80)),
                ('entity_pk', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('entity_key', models.CharField(db_index=True, max_length=512)),
                ('entity_revision', models.CharField(blank=True, default='', max_length=128)),
                ('relation_role', models.CharField(choices=[('PRIMARY', 'Entidad principal'), ('CONTAINS', 'Contiene'), ('BELONGS_TO', 'Pertenece a'), ('REFERENCES', 'Referencia'), ('RESPONDS_TO', 'Responde a'), ('SUPERSEDES', 'Reemplaza'), ('ATTACHMENT_OF', 'Adjunto de'), ('RELATED', 'Relacionado')], db_index=True, default='RELATED', max_length=32)),
                ('relation_basis', models.CharField(choices=[('DIRECT', 'Relación directa'), ('FOREIGN_KEY', 'ForeignKey existente'), ('EXACT_CODE', 'Código exacto'), ('REFERENCE', 'Campo de referencia'), ('IMPORT_MAPPING', 'Relación desde importación'), ('CONTENT', 'Coincidencia de contenido'), ('INFERRED', 'Relación inferida'), ('MANUAL', 'Relación manual')], db_index=True, default='DIRECT', max_length=32)),
                ('confidence', models.PositiveSmallIntegerField(default=100, help_text='100 = relación comprobada. Valores menores permiten identificar relaciones inferidas.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='transmital.projectevent')),
            ],
            options={
                'verbose_name': 'Relación de evento',
                'verbose_name_plural': 'Relaciones de eventos',
                'indexes': [models.Index(fields=['entity_type', 'entity_key'], name='trace_entity_key_idx'), models.Index(fields=['entity_type', 'entity_pk'], name='trace_entity_pk_idx'), models.Index(fields=['event', 'relation_role'], name='trace_event_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'entity_type', 'entity_key', 'relation_role'), name='uniq_project_event_link')],
            },
        ),
    ]
