# Generated by Django 5.2.8 on 2026-03-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDIImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rdi/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('snapshot_datetime', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RDI Import',
                'verbose_name_plural': 'RDI Imports',
                'ordering': ['-snapshot_datetime', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RDIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=400)),
                ('question', models.TextField(blank=True, default='')),
                ('suggested_answer', models.TextField(blank=True, default='')),
                ('location_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REMITIDA', 'Remitida'), ('ABIERTA', 'Abierta'), ('RESPONDIDA', 'Respondida'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada'), ('NULA', 'Nula')], default='NULA', max_length=12)),
                ('response', models.TextField(blank=True, default='')),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('assignee_type', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('associated_to_document', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('distribution_list', models.TextField(blank=True, default='')),
                ('cost_impact', models.CharField(blank=True, default='', max_length=60)),
                ('schedule_impact', models.CharField(blank=True, default='', max_length=60)),
                ('priority', models.CharField(blank=True, default='', max_length=60)),
                ('discipline', models.TextField(blank=True, default='')),
                ('category', models.TextField(blank=True, default='')),
                ('reference', models.TextField(blank=True, default='')),
                ('last_snapshot_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_diff_fields', models.TextField(blank=True, default='')),
                ('last_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdi.rdiimport')),
            ],
            options={
                'verbose_name': 'RDI Record',
                'verbose_name_plural': 'RDI Records',
                'ordering': ['csv_id'],
            },
        ),
    ]
