# Generated by Django 5.2.8 on 2026-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdi', '0002_rdirecord_informado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanosImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='planos/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('snapshot_datetime', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planos Import',
                'verbose_name_plural': 'Planos Imports',
                'ordering': ['-snapshot_datetime', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanosRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.TextField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(blank=True, default='', max_length=80)),
                ('size', models.CharField(blank=True, default='', max_length=80)),
                ('last_update_raw', models.CharField(blank=True, default='', max_length=120)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('last_upload_raw', models.CharField(blank=True, default='', max_length=120)),
                ('last_upload_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('review_mark', models.CharField(blank=True, default='', max_length=255)),
                ('incidence', models.CharField(blank=True, default='', max_length=255)),
                ('sdi', models.CharField(blank=True, default='', max_length=255)),
                ('review_status', models.CharField(blank=True, default='', max_length=255)),
                ('set_name', models.CharField(blank=True, default='', max_length=255)),
                ('issue_date_raw', models.CharField(blank=True, default='', max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('sheet_number', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.TextField(blank=True, default='')),
                ('revision', models.CharField(blank=True, default='', max_length=255)),
                ('last_snapshot_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_diff_fields', models.TextField(blank=True, default='')),
                ('last_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdi.planosimport')),
            ],
            options={
                'verbose_name': 'Planos Record',
                'verbose_name_plural': 'Planos Records',
                'ordering': ['name', 'folder_path'],
                'constraints': [models.UniqueConstraint(fields=('folder_path', 'name'), name='uniq_planos_folder_name')],
            },
        ),
    ]
