# Generated by Django 5.2.8 on 2026-04-30 12:10

import rdi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdi', '0004_planosinicialesimport_planosinicialesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosinicialesrecord',
            name='column_headers_order',
            field=models.JSONField(default=rdi.models._empty_json_list),
        ),
        migrations.AlterField(
            model_name='planosinicialesrecord',
            name='columns_json',
            field=models.JSONField(default=rdi.models._empty_json_dict),
        ),
    ]
