# Generated by Django 5.2.8 on 2026-07-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdi', '0005_alter_planosinicialesrecord_column_headers_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanosDiferenciasMensualesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(db_index=True, unique=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('computed_by', models.CharField(blank=True, default='', max_length=255)),
                ('total_differences', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Planos Diferencias Mensuales (Snapshot)',
                'verbose_name_plural': 'Planos Diferencias Mensuales (Snapshots)',
                'ordering': ['-month_start'],
            },
        ),
        migrations.CreateModel(
            name='PlanosDiferenciasMensualesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, default='', max_length=32)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('version_matriz', models.CharField(blank=True, default='', max_length=255)),
                ('version_planos', models.CharField(blank=True, default='', max_length=255)),
                ('version_transition', models.CharField(blank=True, default='', max_length=400)),
                ('planos_last_update', models.DateField(blank=True, null=True)),
                ('iniciales_last_date', models.DateField(blank=True, null=True)),
                ('iniciales_version', models.CharField(blank=True, default='', max_length=255)),
                ('iniciales_rev_raw', models.CharField(blank=True, default='', max_length=255)),
                ('folder_path', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rdi.planosdiferenciasmensualessnapshot')),
            ],
            options={
                'verbose_name': 'Planos Diferencias Mensuales (Record)',
                'verbose_name_plural': 'Planos Diferencias Mensuales (Records)',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'code'), name='uniq_planos_diferencias_mensuales_snapshot_code')],
            },
        ),
    ]
