# Generated by Django 5.2.8 on 2026-03-01 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExecutingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'EECC',
                'verbose_name_plural': 'EECC',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.executingcompany')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.process')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.project')),
            ],
            options={
                'verbose_name': 'Secuencia de documento',
                'verbose_name_plural': 'Secuencias de documento',
                'constraints': [models.UniqueConstraint(fields=('project', 'company', 'process', 'doc_type'), name='uniq_sequence_per_combo')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('revision', models.CharField(blank=True, default='0', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido'), ('OBSOLETE', 'Obsoleto')], default='DRAFT', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.executingcompany')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.process')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.project')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'company', 'process', 'doc_type'], name='documents_d_project_416057_idx'), models.Index(fields=['code'], name='documents_d_code_ec4445_idx')],
            },
        ),
    ]
