# Generated by Django 5.2.8 on 2026-03-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_folder_content_extract'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_attachments/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document')),
            ],
            options={
                'verbose_name': 'Adjunto de documento',
                'verbose_name_plural': 'Adjuntos de documento',
                'ordering': ['created_at'],
            },
        ),
    ]
