# Generated by Django 5.2.8 on 2026-03-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.CharField(help_text='Emails separados por coma o punto y coma', max_length=1024)),
                ('copia', models.CharField(blank=True, default='', help_text='CC, separados por coma o punto y coma', max_length=1024)),
                ('asunto', models.CharField(max_length=512)),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('enviado_ok', models.BooleanField(default=False, help_text='True si el envío SMTP fue exitoso')),
                ('error_msg', models.CharField(blank=True, default='', max_length=512)),
                ('enviado_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correo enviado',
                'verbose_name_plural': 'Correos enviados',
                'ordering': ['-enviado_at'],
            },
        ),
    ]
