# Generated by Django 5.2.8 on 2026-03-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_correo_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoenviado',
            name='adjuntos_nombres',
            field=models.CharField(blank=True, default='', help_text='Nombres de archivos adjuntos separados por coma', max_length=1024),
        ),
    ]
