# Generated by Django 5.2.8 on 2026-03-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_correo_adjuntos_nombres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del grupo (ej: odata, general, bms)', max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('emails', models.TextField(blank=True, default='', help_text='Un correo por línea, o separados por coma/punto y coma')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de correos (CC)',
                'verbose_name_plural': 'Grupos de correos (CC)',
                'ordering': ['nombre'],
            },
        ),
    ]
