# Generated by Django 5.2.8 on 2026-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_add_grupo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido'), ('OBSOLETE', 'Obsoleto'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PENDING', 'Pendiente'), ('PRELIMINAR', 'Preliminar'), ('SOLO_INFO', 'Solo-Info'), ('REVISION', 'Revisión'), ('REV_Y_CONOC', 'Rev-y-conoc.'), ('CONOCIMIENTO', 'Conocimiento'), ('CONSTRUCCION', 'Construcción'), ('COMENTARIOS', 'Comentarios'), ('DEVUELTO_COM', 'Devuelto-Comentarios'), ('CONOC_CORREC', 'Conoc-con-correc.'), ('CERTIFICADO', 'Certificado'), ('ENT_FINAL', 'Entrega-Final')], default='DRAFT', max_length=12),
        ),
    ]
