# Generated by Django 5.2.8 on 2026-03-25 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_informado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Fin de sesión')], db_index=True, max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de sesión',
                'verbose_name_plural': 'Logs de sesión',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
