# Generated by Django 5.2.8 on 2026-09-27 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_correoenviado_text_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estado_liberacion',
            field=models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE', 'Pendiente de liberación'), ('INFORMADA', 'Liberación informada'), ('LIBERADO', 'Liberado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='NO_APLICA', help_text='Estado de liberación oficial. Una revisión 0 no implica por sí sola que el documento esté liberado.', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='fecha_liberacion',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha efectiva en que el documento fue liberado oficialmente.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fuente_liberacion',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Correo electrónico'), ('SELLO', 'Sello en documento'), ('BIM', 'Plataforma BIM'), ('MANUAL', 'Confirmación manual'), ('OTRA', 'Otra fuente')], default='', help_text='Fuente principal que informó o confirmó la liberación.', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='liberacion_observacion',
            field=models.TextField(blank=True, default='', help_text='Observaciones del proceso de liberación del documento.'),
        ),
        migrations.AddField(
            model_name='document',
            name='liberacion_observada_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el sistema o un usuario conoció/registró la liberación.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='liberacion_referencia',
            field=models.CharField(blank=True, default='', help_text='Referencia breve de la evidencia: asunto de correo, comunicación, número de aviso u otra referencia.', max_length=512),
        ),
        migrations.AddField(
            model_name='document',
            name='liberacion_registrada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró la información de liberación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_liberacion_registrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='liberacion_transmittal',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código o referencia del transmittal asociado a la liberación. Se mantiene como texto para permitir históricos aún no cargados.', max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='sello_liberado_verificado',
            field=models.BooleanField(db_index=True, default=False, help_text='True cuando se verificó visualmente en el archivo el sello oficial de liberación.'),
        ),
        migrations.AddField(
            model_name='document',
            name='sello_verificado_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se verificó el sello en el documento.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sello_verificado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que verificó visualmente el sello de liberación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_sello_verificado', to=settings.AUTH_USER_MODEL),
        ),
    ]
