# Generated by Django 5.2.8 on 2026-04-12 22:02

import equipos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposlibro',
            name='file',
            field=models.FileField(upload_to=equipos.models.equipos_libro_upload_to),
        ),
    ]
