# Generated by Django 5.2.8 on 2026-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_gantttask_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantttask',
            name='avance_planificado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gantttask',
            name='trabajo_completado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
